# Generated by Django 4.1.7 on 2023-02-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uniqueId',
            field=models.TextField(default='98594fn84ru', max_length=50),
            preserve_default=False,
        ),
    ]
