# Generated by Django 4.1.7 on 2023-02-22 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_image_uniqueid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('type', models.TextField(choices=[('NATL', 'National Election'), ('STAT', 'State Election'), ('LOCL', 'Local Election')], max_length=4)),
                ('name', models.TextField(max_length=100)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('phone', models.IntegerField()),
                ('education', models.TextField()),
                ('dateOfBirth', models.DateField()),
                ('description', models.TextField()),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.election')),
            ],
        ),
    ]
