# Generated by Django 4.1.7 on 2023-02-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_election_electioncandidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='startdate',
            new_name='startDate',
        ),
        migrations.AlterField(
            model_name='electioncandidate',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
