# Generated by Django 4.1.7 on 2023-02-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_startdate_election_startdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electioncandidate',
            name='image',
        ),
    ]
