# Generated by Django 4.1.7 on 2023-02-22 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_electioncandidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electioncandidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.election'),
        ),
    ]
